export const schema = {
  users: {
    id: "text",
    first_name: "text",
    last_name: "text",
    role: "text",
    email: "text",
    password: "text",
    is_deleted: "boolean",
    is_admin: "boolean",
    address: "text",
    receipt_template: "text",
    commission: "numeric",
    mobile: "text",
    referral: "text",
    user_level: "integer",
    com_rate: "numeric",
    com_portion: "numeric",
    device_id: "text",
    user_id: "text",
    coordinates: "text",
    gross_today: "numeric",
    app_version: "text",
    last_summary: "timestamp",
    configuration: "json",
    uplines: "json",
    created_at: "timestamp",
    updated_at: "timestamp",
  },

  bettings: {
    id: "text",
    is_complete: "boolean",
    is_deleted: "boolean",
    is_validated: "timestamp",
    timestamp: "timestamp",
    input_type: "text",
    straight: "numeric",
    ramble: "numeric",
    gross: "numeric",
    net: "numeric",
    is_print: "boolean",
    is_win_to: "boolean",
    collector: "text",
    owner_id: "text",
    print_copy: "integer",
    draw_id: "text",
    user_id: "text",
    file_url: "text",
    note: "text",
    contact: "text",
    ticket_no: "text",
    winning: "numeric",
    game_time: "text",
    hits: "json",
    commissions: "json",
    combinations: "json",
    uplines: "json",
    created_at: "timestamp",
    updated_at: "timestamp",
  },

  draws: {
    id: "text",
    game_type: "text",
    game_time: "text",
    combination: "text",
    gross_total: "numeric",
    win_total: "numeric",
    net_total: "numeric",
    sold_out_total: "numeric",
    draw_date: "timestamp",
    is_win_to: "boolean",
    tip_url: "text",
    is_deleted: "boolean",
    created_at: "timestamp",
    updated_at: "timestamp",
  },

  master_combinations: {
    id: "text",
    digit: "text",
    straight_limit: "numeric",
    ramble_limit: "numeric",
    ramble_total: "numeric",
    straight_total: "numeric",
    is_win_to: "boolean",
    risk_level: "text",
    win_frequency: "integer",
    straight_max_limit: "numeric",
    ramble_max_limit: "numeric",
    is_deleted: "boolean",
    created_at: "timestamp",
    updated_at: "timestamp",
  },

  messages: {
    id: "text",
    created_by: "text",
    message: "text",
    status: "text",
    recipient: "text",
    is_flash: "boolean",
    recipient_name: "text",
    conversations: "json",
    is_deleted: "boolean",
    created_at: "timestamp",
    updated_at: "timestamp",
  },

  cashflow: {
    id: "text",
    amount: "numeric",
    description: "text",
    input_type: "text",
    is_deleted: "boolean",
    owner: "text",
    owner_name: "text",
    user: "text",
    updated_by: "text",
    created_at: "timestamp",
    updated_at: "timestamp",
  },
};
