export const SET_LOADING = 'SET_LOADING';
export const SET_USER = 'SET_USER';
export const SET_COLLECTOR = 'SET_COLLECTOR';
export const STOP_LOADING = 'STOP_LOADING';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_APK_URL = 'SET_APK_URL';
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'
export const OPEN_UPDATE_MODAL = 'OPEN_UPDATE_MODAL';
export const CLOSE_UPDATE_MODAL = 'CLOSE_UPDATE_MODAL';
export const SET_DEVICE_ADDRESS = 'SET_DEVICE_ADDRESS';
export const CLEAR_DEVICE_ADDRESS = 'CLEAR_DEVICE_ADDRESS';
export const SET_USER_CONFIG = 'SET_USER_CONFIG';
export const OPEN_CONFIRMATION_MODAL = 'OPEN_CONFIRMATION_MODAL';
export const CLOSE_CONFIRMATION_MODAL = 'CLOSE_CONFIRMATION_MODAL';
export const OPEN_WARNING_MODAL = 'OPEN_WARNING_MODAL';
export const CLOSE_WARNING_MODAL = 'CLOSE_WARNING_MODAL';
export const SET_SUMMARIZED_USER = 'SET_SUMMARIZED_USER';
export const INCREMENT_UNREAD_MESSAGES = 'INCREMENT_UNREAD_MESSAGES';
export const DECREMENT_UNREAD_MESSAGES = 'DECREMENT_UNREAD_MESSAGES';
export const OPEN_ALERT_MODAL = 'SET_ALERT_MODAL';
export const CLOSE_ALERT_MODAL = 'CLEAR_ALERT_MODAL';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';


// Risk controller
export const SET_BETTING_LIMITS = 'SET_BETTING_LIMITS';
export const UPDATE_BETTING_RISK_TIER = 'UPDATE_BETTING_RISK_TIER';
export const UPDATE_BETTING_USAGE = 'UPDATE_BETTING_USAGE';

// src/redux/actions/types.js (add these to your existing types)
export const BETTING_ACTION_TYPES = {
  // Bettings
  CREATE_BETTING_REQUEST: 'CREATE_BETTING_REQUEST',
  CREATE_BETTING_SUCCESS: 'CREATE_BETTING_SUCCESS',
  CREATE_BETTING_FAILURE: 'CREATE_BETTING_FAILURE',
  
  UPDATE_BETTING_REQUEST: 'UPDATE_BETTING_REQUEST',
  UPDATE_BETTING_SUCCESS: 'UPDATE_BETTING_SUCCESS',
  UPDATE_BETTING_FAILURE: 'UPDATE_BETTING_FAILURE',
  
  DELETE_BETTING_REQUEST: 'DELETE_BETTING_REQUEST',
  DELETE_BETTING_SUCCESS: 'DELETE_BETTING_SUCCESS',
  DELETE_BETTING_FAILURE: 'DELETE_BETTING_FAILURE',
  
  FETCH_BETTINGS_REQUEST: 'FETCH_BETTINGS_REQUEST',
  FETCH_BETTINGS_SUCCESS: 'FETCH_BETTINGS_SUCCESS',
  FETCH_BETTINGS_FAILURE: 'FETCH_BETTINGS_FAILURE',
  
  // Draws
  CREATE_DRAW_REQUEST: 'CREATE_DRAW_REQUEST',
  CREATE_DRAW_SUCCESS: 'CREATE_DRAW_SUCCESS',
  CREATE_DRAW_FAILURE: 'CREATE_DRAW_FAILURE',
  
  UPDATE_DRAW_REQUEST: 'UPDATE_DRAW_REQUEST',
  UPDATE_DRAW_SUCCESS: 'UPDATE_DRAW_SUCCESS',
  UPDATE_DRAW_FAILURE: 'UPDATE_DRAW_FAILURE',
  
  DELETE_DRAW_REQUEST: 'DELETE_DRAW_REQUEST',
  DELETE_DRAW_SUCCESS: 'DELETE_DRAW_SUCCESS',
  DELETE_DRAW_FAILURE: 'DELETE_DRAW_FAILURE',
  
  FETCH_DRAWS_REQUEST: 'FETCH_DRAWS_REQUEST',
  FETCH_DRAWS_SUCCESS: 'FETCH_DRAWS_SUCCESS',
  FETCH_DRAWS_FAILURE: 'FETCH_DRAWS_FAILURE',
  
  // Master Combinations
  CREATE_MASTER_COMBINATION_REQUEST: 'CREATE_MASTER_COMBINATION_REQUEST',
  CREATE_MASTER_COMBINATION_SUCCESS: 'CREATE_MASTER_COMBINATION_SUCCESS',
  CREATE_MASTER_COMBINATION_FAILURE: 'CREATE_MASTER_COMBINATION_FAILURE',
  
  UPDATE_MASTER_COMBINATION_REQUEST: 'UPDATE_MASTER_COMBINATION_REQUEST',
  UPDATE_MASTER_COMBINATION_SUCCESS: 'UPDATE_MASTER_COMBINATION_SUCCESS',
  UPDATE_MASTER_COMBINATION_FAILURE: 'UPDATE_MASTER_COMBINATION_FAILURE',
  
  DELETE_MASTER_COMBINATION_REQUEST: 'DELETE_MASTER_COMBINATION_REQUEST',
  DELETE_MASTER_COMBINATION_SUCCESS: 'DELETE_MASTER_COMBINATION_SUCCESS',
  DELETE_MASTER_COMBINATION_FAILURE: 'DELETE_MASTER_COMBINATION_FAILURE',
  
  FETCH_MASTER_COMBINATIONS_REQUEST: 'FETCH_MASTER_COMBINATIONS_REQUEST',
  FETCH_MASTER_COMBINATIONS_SUCCESS: 'FETCH_MASTER_COMBINATIONS_SUCCESS',
  FETCH_MASTER_COMBINATIONS_FAILURE: 'FETCH_MASTER_COMBINATIONS_FAILURE',
};

// Add these to your existing DATA_ACTION_TYPES if needed
export const DATA_ACTION_TYPES = {
  // ... your existing types
  FETCH_BETTING_BY_ID_REQUEST: 'FETCH_BETTING_BY_ID_REQUEST',
  FETCH_BETTING_BY_ID_SUCCESS: 'FETCH_BETTING_BY_ID_SUCCESS',
  FETCH_BETTING_BY_ID_FAILURE: 'FETCH_BETTING_BY_ID_FAILURE',
  
  FETCH_DRAW_BY_ID_REQUEST: 'FETCH_DRAW_BY_ID_REQUEST',
  FETCH_DRAW_BY_ID_SUCCESS: 'FETCH_DRAW_BY_ID_SUCCESS',
  FETCH_DRAW_BY_ID_FAILURE: 'FETCH_DRAW_BY_ID_FAILURE',
  
  FETCH_MASTER_COMBINATION_BY_ID_REQUEST: 'FETCH_MASTER_COMBINATION_BY_ID_REQUEST',
  FETCH_MASTER_COMBINATION_BY_ID_SUCCESS: 'FETCH_MASTER_COMBINATION_BY_ID_SUCCESS',
  FETCH_MASTER_COMBINATION_BY_ID_FAILURE: 'FETCH_MASTER_COMBINATION_BY_ID_FAILURE',
  INCREMENT_DATA_VERSION: 'INCREMENT_DATA_VERSION',

};